name: Build and Publish Docker
on:
  push:
    branches:
      - master
jobs:
     build:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@master
       - name: Publish to Docker Repository
         uses: elgohr/Publish-Docker-Github-Action@v4
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: 905447797/image-syncer
